using SeWzc.X11Sharp.Handles;

namespace SeWzc.X11Sharp;

public static class X11Atoms
{
    public static X11Atom PRIMARY { get; } = new(1);
    public static X11Atom SECONDARY { get; } = new(2);
    public static X11Atom ARC { get; } = new(3);
    public static X11Atom ATOM { get; } = new(4);
    public static X11Atom BITMAP { get; } = new(5);
    public static X11Atom CARDINAL { get; } = new(6);
    public static X11Atom COLORMAP { get; } = new(7);
    public static X11Atom CURSOR { get; } = new(8);
    public static X11Atom CUT_BUFFER0 { get; } = new(9);
    public static X11Atom CUT_BUFFER1 { get; } = new(10);
    public static X11Atom CUT_BUFFER2 { get; } = new(11);
    public static X11Atom CUT_BUFFER3 { get; } = new(12);
    public static X11Atom CUT_BUFFER4 { get; } = new(13);
    public static X11Atom CUT_BUFFER5 { get; } = new(14);
    public static X11Atom CUT_BUFFER6 { get; } = new(15);
    public static X11Atom CUT_BUFFER7 { get; } = new(16);
    public static X11Atom DRAWABLE { get; } = new(17);
    public static X11Atom FONT { get; } = new(18);
    public static X11Atom INTEGER { get; } = new(19);
    public static X11Atom PIXMAP { get; } = new(20);
    public static X11Atom POINT { get; } = new(21);
    public static X11Atom RECTANGLE { get; } = new(22);
    public static X11Atom RESOURCE_MANAGER { get; } = new(23);
    public static X11Atom RGB_COLOR_MAP { get; } = new(24);
    public static X11Atom RGB_BEST_MAP { get; } = new(25);
    public static X11Atom RGB_BLUE_MAP { get; } = new(26);
    public static X11Atom RGB_DEFAULT_MAP { get; } = new(27);
    public static X11Atom RGB_GRAY_MAP { get; } = new(28);
    public static X11Atom RGB_GREEN_MAP { get; } = new(29);
    public static X11Atom RGB_RED_MAP { get; } = new(30);
    public static X11Atom STRING { get; } = new(31);
    public static X11Atom VISUALID { get; } = new(32);
    public static X11Atom WINDOW { get; } = new(33);
    public static X11Atom WM_COMMAND { get; } = new(34);
    public static X11Atom WM_HINTS { get; } = new(35);
    public static X11Atom WM_CLIENT_MACHINE { get; } = new(36);
    public static X11Atom WM_ICON_NAME { get; } = new(37);
    public static X11Atom WM_ICON_SIZE { get; } = new(38);
    public static X11Atom WM_NAME { get; } = new(39);
    public static X11Atom WM_NORMAL_HINTS { get; } = new(40);
    public static X11Atom WM_SIZE_HINTS { get; } = new(41);
    public static X11Atom WM_ZOOM_HINTS { get; } = new(42);
    public static X11Atom MIN_SPACE { get; } = new(43);
    public static X11Atom NORM_SPACE { get; } = new(44);
    public static X11Atom MAX_SPACE { get; } = new(45);
    public static X11Atom END_SPACE { get; } = new(46);
    public static X11Atom SUPERSCRIPT_X { get; } = new(47);
    public static X11Atom SUPERSCRIPT_Y { get; } = new(48);
    public static X11Atom SUBSCRIPT_X { get; } = new(49);
    public static X11Atom SUBSCRIPT_Y { get; } = new(50);
    public static X11Atom UNDERLINE_POSITION { get; } = new(51);
    public static X11Atom UNDERLINE_THICKNESS { get; } = new(52);
    public static X11Atom STRIKEOUT_ASCENT { get; } = new(53);
    public static X11Atom STRIKEOUT_DESCENT { get; } = new(54);
    public static X11Atom ITALIC_ANGLE { get; } = new(55);
    public static X11Atom X_HEIGHT { get; } = new(56);
    public static X11Atom QUAD_WIDTH { get; } = new(57);
    public static X11Atom WEIGHT { get; } = new(58);
    public static X11Atom POINT_SIZE { get; } = new(59);
    public static X11Atom RESOLUTION { get; } = new(60);
    public static X11Atom COPYRIGHT { get; } = new(61);
    public static X11Atom NOTICE { get; } = new(62);
    public static X11Atom FONT_NAME { get; } = new(63);
    public static X11Atom FAMILY_NAME { get; } = new(64);
    public static X11Atom FULL_NAME { get; } = new(65);
    public static X11Atom CAP_HEIGHT { get; } = new(66);
    public static X11Atom WM_CLASS { get; } = new(67);
    public static X11Atom WM_TRANSIENT_FOR { get; } = new(68);
    public static X11Atom LAST_PREDEFINED { get; } = new(68);
}
